#!/bin/bash

###### KEYCLOAK ######
KEYCLOAK_DB_NAME=${KEYCLOAK_DB_NAME}
KEYCLOAK_DB_USER=${KEYCLOAK_DB_USER}
KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}

echo "Creating user and database for Keycloak..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
    CREATE DATABASE $KEYCLOAK_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_NAME TO $KEYCLOAK_DB_USER;
    ALTER DATABASE $KEYCLOAK_DB_NAME OWNER TO $KEYCLOAK_DB_USER;
EOSQL

echo "User and database for Keycloak created successfully."

###### ZABBIX ######
ZABBIX_DB_NAME=${ZABBIX_DB_NAME}
ZABBIX_DB_USER=${ZABBIX_DB_USER}
ZABBIX_DB_PASSWORD=${ZABBIX_DB_PASSWORD}

echo "Creating user and database for Zabbix..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $ZABBIX_DB_USER WITH PASSWORD '$ZABBIX_DB_PASSWORD';
    CREATE DATABASE $ZABBIX_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $ZABBIX_DB_NAME TO $ZABBIX_DB_USER;
    ALTER DATABASE $ZABBIX_DB_NAME OWNER TO $ZABBIX_DB_USER;
EOSQL

echo "User and database for Zabbix created successfully."

###### GRAFANA ######
GRAFANA_DB_NAME=${GRAFANA_DB_NAME}
GRAFANA_DB_USER=${GRAFANA_DB_USER}
GRAFANA_DB_PASSWORD=${GRAFANA_DB_PASSWORD}

echo "Creating user and database for Grafana..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $GRAFANA_DB_USER WITH PASSWORD '$GRAFANA_DB_PASSWORD';
    CREATE DATABASE $GRAFANA_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $GRAFANA_DB_NAME TO $GRAFANA_DB_USER;
    ALTER DATABASE $GRAFANA_DB_NAME OWNER TO $GRAFANA_DB_USER;
EOSQL

echo "User and database for Grafana created successfully."